#!/usr/bin/env bash
# voltdots — install.sh
# Creates symlinks from ~/.voltdots to ~/.config
# Safe to run multiple times — existing symlinks are updated

DOTFILES="$HOME/.voltdots"
CONFIG="$HOME/.config"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[info]${NC} $1"; }
success() { echo -e "${GREEN}[ok]${NC} $1"; }
warning() { echo -e "${YELLOW}[warn]${NC} $1"; }
error()   { echo -e "${RED}[error]${NC} $1"; }

# --- Create symlink ---
link() {
    local src="$1"
    local dst="$2"
    mkdir -p "$(dirname "$dst")"
    if [[ -L "$dst" ]]; then
        rm "$dst"
    elif [[ -e "$dst" ]]; then
        warning "Backing up existing $dst → $dst.bak"
        mv "$dst" "$dst.bak"
    fi
    ln -s "$src" "$dst"
    success "Linked $dst → $src"
}

# --- Install dependencies ---
install_deps() {
    info "Installing dependencies..."

    local pkgs=(
        hyprland waybar fuzzel wofi swaync awww
        hyprlock hypridle swayosd
        grim slurp wl-clipboard cliphist
        thunar nautilus firefox
        fcitx5 fcitx5-gtk fcitx5-qt
        blueman network-manager-applet
        polkit-gnome celluloid zathura
        brightnessctl playerctl
        libnotify jq curl
        wlr-randr iio-sensor-proxy
        ttf-jetbrains-mono-nerd noto-fonts
        papirus-icon-theme
        pipewire wireplumber
        gsimplecal
    )

    local aur_pkgs=(
        gpu-screen-recorder
    )

    if command -v pacman > /dev/null; then
        info "Installing pacman packages..."
        sudo pacman -S --needed --noconfirm "${pkgs[@]}"

        if command -v yay > /dev/null; then
            info "Installing AUR packages..."
            yay -S --needed --noconfirm "${aur_pkgs[@]}"
        elif command -v paru > /dev/null; then
            info "Installing AUR packages..."
            paru -S --needed --noconfirm "${aur_pkgs[@]}"
        else
            warning "No AUR helper found — install manually: ${aur_pkgs[*]}"
        fi
    else
        warning "pacman not found — skipping dependency install"
        info "Install manually: ${pkgs[*]} ${aur_pkgs[*]}"
    fi
}

# --- Create custom dirs ---
init_custom() {
    info "Initializing custom dirs..."

    local dirs=(
        "$DOTFILES/hypr/custom"
        "$DOTFILES/waybar/custom"
        "$DOTFILES/swaync/custom"
    )

    for dir in "${dirs[@]}"; do
        [[ ! -d "$dir" ]] && mkdir -p "$dir" && success "Created $dir"
    done

    local custom_files=(
        "$DOTFILES/hypr/custom/env.conf"
        "$DOTFILES/hypr/custom/monitors.conf"
        "$DOTFILES/hypr/custom/keybinds.conf"
        "$DOTFILES/hypr/custom/rules.conf"
        "$DOTFILES/hypr/custom/execs.conf"
        "$DOTFILES/hypr/custom/defaults.conf"
    )

    for file in "${custom_files[@]}"; do
        if [[ ! -f "$file" ]]; then
            echo "# Machine-specific override — $(basename "$file")" > "$file"
            success "Created empty $file"
        fi
    done

    # Always regenerate env with correct paths
    cat > "$DOTFILES/hypr/custom/env.conf" << ENVEOF
# auto-generated by install.sh
env = VOLTSCRIPTS,$DOTFILES/scripts
ENVEOF
    success "Generated custom/env.conf"
}

# --- Symlinks ---
create_links() {
    info "Creating symlinks..."

    link "$DOTFILES/hypr/default/hyprland.conf" "$CONFIG/hypr/hyprland.conf"
    link "$DOTFILES/waybar/default"              "$CONFIG/waybar"
    link "$DOTFILES/swaync/default"              "$CONFIG/swaync"
    link "$DOTFILES/hyprlock/hyprlock.conf"      "$CONFIG/hypr/hyprlock.conf"
    link "$DOTFILES/hypridle/hypridle.conf"      "$CONFIG/hypr/hypridle.conf"
    link "$DOTFILES/swayosd"                     "$CONFIG/swayosd"
    link "$DOTFILES/matugen"                     "$CONFIG/matugen"
    link "$DOTFILES/fuzzel"                      "$CONFIG/fuzzel"
    link "$DOTFILES/wofi"                        "$CONFIG/wofi"
}

# --- Make scripts executable ---
make_executable() {
    info "Setting script permissions..."
    chmod +x "$DOTFILES/scripts/"*.sh
    success "Scripts are executable"
}

# --- Main ---
echo -e "${BLUE}"
echo "  ██╗   ██╗ ██████╗ ██╗  ████████╗██████╗  ██████╗ ████████╗███████╗"
echo "  ██║   ██║██╔═══██╗██║  ╚══██╔══╝██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝"
echo "  ██║   ██║██║   ██║██║     ██║   ██║  ██║██║   ██║   ██║   ███████╗"
echo "  ╚██╗ ██╔╝██║   ██║██║     ██║   ██║  ██║██║   ██║   ██║   ╚════██║"
echo "   ╚████╔╝ ╚██████╔╝███████╗██║   ██████╔╝╚██████╔╝   ██║   ███████║"
echo "    ╚═══╝   ╚═════╝ ╚══════╝╚═╝   ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝"
echo -e "${NC}"
echo "  BKPView theme — Hyprland vanilla dotfiles"
echo ""

# Parse args
SKIP_DEPS=false
[[ "$1" == "--skip-deps" ]] && SKIP_DEPS=true

[[ "$SKIP_DEPS" == false ]] && install_deps

init_custom
create_links
make_executable

echo ""
info "Detecting monitors..."
"$DOTFILES/scripts/detect_monitors.sh"

echo ""
success "voltdots installed successfully!"
echo ""
info "Next steps:"
echo "  1. Review ~/.voltdots/hypr/custom/monitors.conf"
echo "  2. Edit ~/.voltdots/hypr/custom/defaults.conf — set your preferred apps"
echo "  3. Add wallpapers to ~/Pictures/Wallpapers"
echo "  4. Start Hyprland"
echo ""
info "Skip deps on next run: ./install.sh --skip-deps"
