# voltdots — hyprlock.conf
# BKPView theme — dark carbon, electric blue

general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.02
    contrast = 1.1
    brightness = 0.6
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(1a6cf5)
    inner_color = rgb(0d0f12)
    font_color = rgb(7eb8f7)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 8
    check_color = rgb(1a6cf5)
    fail_color = rgb(f5421a)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    capslock_color = rgb(f5c51a)
    halign = center
    valign = center
    position = 0, -120
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(7eb8f7)
    font_size = 72
    font_family = Sans Bold
    halign = center
    valign = center
    position = 0, 80
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgb(5a8fc2)
    font_size = 18
    font_family = Sans
    halign = center
    valign = center
    position = 0, 10
}
