# voltdots — general.conf
# General Hyprland settings

input {
    follow_mouse = 0        # 0 = click to focus, 1 = focus on hover
    sensitivity = 0
    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
    }
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(1a6cf5ee) rgba(7eb8f7ee) 45deg
    col.inactive_border = rgba(0a0c1099)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.95
    dim_strength = 0.5
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
        xray = false
    }
    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(1a6cf540)
    }
}

dwindle {
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
