# voltdots — hyprland.conf
# Ne jamais modifier ce fichier directement
# Utiliser hypr/custom/ pour les overrides machine

# Core
source = ~/.dotfiles/hypr/default/env.conf
source = ~/.dotfiles/hypr/default/animations.conf
source = ~/.dotfiles/hypr/default/rules.conf
source = ~/.dotfiles/hypr/default/keybinds.conf
source = ~/.dotfiles/hypr/default/execs.conf

# Overrides machine-specific
source = ~/.dotfiles/hypr/custom/env.conf
source = ~/.dotfiles/hypr/custom/monitors.conf
source = ~/.dotfiles/hypr/custom/keybinds.conf
source = ~/.dotfiles/hypr/custom/rules.conf
source = ~/.dotfiles/hypr/custom/execs.conf
