# voltdots — rules.conf
# Window and layer rules

# --- Floating windows ---
windowrule = float, class:^(thunar)$, title:^(File Operation Progress)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(pavucontrol-qt)$
windowrule = float, class:^(polkit-gnome-authentication-agent-1)$
windowrule = float, class:^(xdg-desktop-portal-gtk)$
windowrule = float, class:^(file-roller)$
windowrule = float, title:^(Picture-in-Picture)$

# --- Picture in Picture ---
windowrule = keepaspectratio, title:^(Picture-in-Picture)$
windowrule = move 73% 72%, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$

# --- Idle inhibit ---
windowrule = idleinhibit fullscreen, class:^(firefox)$
windowrule = idleinhibit fullscreen, class:^(chromium)$
windowrule = idleinhibit always, class:^(celluloid)$
windowrule = idleinhibit always, class:^(mpv)$
windowrule = idleinhibit always, class:^(vlc)$

# --- Workspace assignments ---
windowrule = workspace 10 silent, class:^(astrill)$
windowrule = float, class:^(astrill)$

# --- Opacity ---
windowrule = opacity 0.95 0.90, class:^(thunar)$
windowrule = opacity 0.95 0.90, class:^(codium)$

# --- Fcitx5 ---
windowrule = nofocus, class:^(fcitx)$
