#!/usr/bin/env bash
# voltdots — detect_monitors.sh
# Auto-detect monitors and generate hypr/custom/monitors.conf
# Safe to run multiple times — only generates if file is empty or missing

MONITORS_CONF="$HOME/.voltdots/hypr/custom/monitors.conf"

# Skip if already configured
if [[ -f "$MONITORS_CONF" ]] && [[ -s "$MONITORS_CONF" ]] && ! grep -q "^# auto-generated" "$MONITORS_CONF"; then
    echo "monitors.conf already configured — skipping"
    exit 0
fi

echo "Auto-detecting monitors..."

# Get connected monitors via hyprctl if Hyprland is running
if command -v hyprctl > /dev/null && hyprctl monitors > /dev/null 2>&1; then
    MONITORS=$(hyprctl monitors -j)
    COUNT=$(echo "$MONITORS" | jq length)
    
    {
        echo "# auto-generated by detect_monitors.sh"
        echo "# Edit this file to customize your monitor setup"
        echo "# See https://wiki.hyprland.org/Configuring/Monitors/"
        echo ""

        local x_offset=0
        for i in $(seq 0 $((COUNT - 1))); do
            name=$(echo "$MONITORS" | jq -r ".[$i].name")
            width=$(echo "$MONITORS" | jq -r ".[$i].width")
            height=$(echo "$MONITORS" | jq -r ".[$i].height")
            refresh=$(echo "$MONITORS" | jq -r ".[$i].refreshRate" | xargs printf "%.0f")
            scale=$(echo "$MONITORS" | jq -r ".[$i].scale")

            echo "monitor = $name, ${width}x${height}@${refresh}, ${x_offset}x0, $scale"
            x_offset=$((x_offset + width))
        done
    } > "$MONITORS_CONF"

# Fallback — use wlr-randr or xrandr if Hyprland not running yet
elif command -v wlr-randr > /dev/null; then
    {
        echo "# auto-generated by detect_monitors.sh"
        echo "# Edit this file to customize your monitor setup"
        echo ""
        wlr-randr 2>/dev/null | grep "^[A-Z]" | while read -r name _; do
            echo "monitor = $name, preferred, auto, 1"
        done
    } > "$MONITORS_CONF"

# Last resort — generate a safe default
else
    {
        echo "# auto-generated by detect_monitors.sh"
        echo "# Could not detect monitors — using safe defaults"
        echo "# Edit this file with your actual monitor configuration"
        echo ""
        echo "# Single monitor fallback"
        echo "monitor = ,preferred,auto,1"
    } > "$MONITORS_CONF"
fi

echo "monitors.conf generated at $MONITORS_CONF"
cat "$MONITORS_CONF"
